print("Write how many cups of coffee you will need:")
cup = int(input(">"))
print("For", cup, "cups of coffee you will need:")
print(cup * 200, "ml of water")
print(cup * 50, "ml of milk")
print(cup * 15, "ml of coffe beans")